// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function GetDirectoryMap(arg1) {
  return window['go']['main']['App']['GetDirectoryMap'](arg1);
}

export function GoHello() {
  return window['go']['main']['App']['GoHello']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
