// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory():Promise<string>;

export function GetDirectoryMap(arg1:string):Promise<Array<string>>;

export function GoHello():Promise<string>;

export function Greet(arg1:string):Promise<string>;
